[package]
name = "kaitai-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
serde = "1.0.193"
serde_yaml = "0.9.29"
thiserror = "1.0.51"
