[package]
name = "ksy-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kaitai-rs = { path = "../kaitai-rs" }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3